spring:
  jpa:
    show-sql: true
    # 格式化输出sql
  #    properties:
  #      hibernate:
  #        format_sql: true
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://101.35.80.154:3306/dynamic?useSSL=false
          username: root
          password: 1234
          driver-class-name:  com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:postgresql://101.35.80.154:5432/aix_db?stringtype=unspecified&currentSchema=aix
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
  quartz:
    # 采用数据库存储方式
    job-store-type: jdbc
    jdbc:
      # 每次启动重新初始化数据库中Quartz相关的表，如果不需要每次启动服务都重新创建表，下面两项可以不配置，事先在数据库中
      initialize-schema: always
      schema: classpath:schema/tables_mysql.sql

# mapper4 配置
mapper:
  mappers: com.platform.quartza.base.repo.BaseMapper
  not-empty: false
  identity: MYSQL
# mybatis 配置
mybatis:
  type-aliases-package: com.platform.quartza.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql