spring:
  jpa:
    show-sql: true
    # 格式化输出sql
  #    properties:
  #      hibernate:
  #        format_sql: true
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.80.154:3306/dynamic?useSSL=false
    username: root
    password: 1234